### NumPy First Steps

### Programming for Data Science
### Last Updated: Jan 15, 2023
---  

### PREREQUISITES
- import
- functions
- for ... in

### SOURCES 
- **Python for Data Analysis, Chapter 4 (be sure to read this)**
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://www.scipy.org/
- https://en.wikipedia.org/wiki/SciPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Take your first steps with numpy
 


### CONCEPTS

- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package


---

### numpy

In this lesson we will explore the python package *numpy*.  
This package is super powerful. 

Our focus will be on:
- importing and calling some random number generating functions
- illustrating operations on ndarrays
- learning how to subset ndarrays

### Motivation

I need a random number! I heard numpy can do that!  

In [2]:
import numpy as np
np.random.randint(1,7) #左闭右开

3

Learn what this function does:

In [9]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

Include the size parameter to generate 10 random integers in [1, 6]

In [10]:
np.random.randint(1,7,10) #10个随机数

array([1, 2, 5, 3, 4, 3, 2, 4, 3, 2])

---

### The ndarray in Numpy

Details [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Represents a multidimensional, homogeneous array of fixed-size items. 

Uses very efficient operations

Arrays should be constructed using `array()`, `zeros()` or `empty()`.

### NumPy ndarray Operations


Create an array with some data

In [11]:
x = np.array(([2,3,1],[3,1,2]))
x

array([[2, 3, 1],
       [3, 1, 2]])

Get the shape of the data (rows, columns)

In [13]:
print(x.shape)

(2, 3)


In [16]:
# generate matrix of random normals 

x = np.random.randn(3, 4) #（matrix个数，元素数）
x

array([[-1.60923791, -1.03572976, -1.72095251, -0.82580827],
       [ 0.52671704, -1.78469112,  0.86490749, -0.7261074 ],
       [ 2.18508259, -0.21686176,  0.22559396,  1.11828162]])

In [3]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

Scale the matrix - notice how this operates elementwise

In [17]:
x * 2

array([[-3.21847582, -2.07145952, -3.44190501, -1.65161654],
       [ 1.05343409, -3.56938225,  1.72981498, -1.4522148 ],
       [ 4.37016519, -0.43372353,  0.45118792,  2.23656325]])

Addition

In [18]:
x + x

array([[-3.21847582, -2.07145952, -3.44190501, -1.65161654],
       [ 1.05343409, -3.56938225,  1.72981498, -1.4522148 ],
       [ 4.37016519, -0.43372353,  0.45118792,  2.23656325]])

Reciprocal

In [19]:
1 / x

array([[-0.62141216, -0.96550281, -0.58107356, -1.21093484],
       [ 1.89855257, -0.56032105,  1.15619301, -1.37720673],
       [ 0.4576486 , -4.61123244,  4.43274278,  0.89422913]])

#### Creating Matrices with Special Structure - can create arrays of zeros, ones, and identity matrices

In [20]:
x=np.zeros(5) #5个0
print(x)

[0. 0. 0. 0. 0.]


In [21]:
x.shape

(5,)

In [22]:
y=np.zeros([5,1]) #5个0，每行一个

In [23]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
y.shape

(5, 1)

In [25]:
z=np.zeros([1,5]) #1行*5列
print(z)

[[0. 0. 0. 0. 0.]]


In [26]:
z.shape

(1, 5)

In [27]:
q=np.zeros((2,3)) #2行*3列
print(q)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
q.shape

(2, 3)

In [29]:
np.ones((2,3))#2行*3列

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.identity(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing and Slicing

In [33]:
z = np.random.randn(5)
z

array([ 0.44771688,  0.23410721,  0.45842442, -1.07739769,  0.07190598])

In [34]:
# select from start to one before end
z[1:4] #从第2个到第4个

array([ 0.23410721,  0.45842442, -1.07739769])

In [35]:
# does this make sense?
z[1:-1] #从第2个到倒数第2个

array([ 0.23410721,  0.45842442, -1.07739769])

In [36]:
# boolean indexing
z[z>0.15] #大于0.15

array([0.44771688, 0.23410721, 0.45842442])

In [37]:
# assignment
z[1] = 3 #第二个变为3
z

array([ 0.44771688,  3.        ,  0.45842442, -1.07739769,  0.07190598])

In [38]:
# 2D
w = np.random.randn(3,3) #3*3随机阵列
w 

array([[ 0.99309875, -0.67303833, -0.72975578],
       [ 0.99222656,  0.30740739, -1.03069519],
       [-0.64110971,  0.73189057, -0.68222625]])

In [39]:
# subset rows and columns
w[1:, :2] #从第二行之后的所有行，从第三列之前的所有列

array([[ 0.99222656,  0.30740739],
       [-0.64110971,  0.73189057]])

#### TRY FOR YOURSELF
Write code to generate a new array *w2* that starts with *w* and sets all negative values to 0.
Then print *w2* and *w*.  

Be sure to use:  
w2 = w.copy()  
or w will get updated as well

In [ ]:
w2 = w.copy() #如果不copy而直接=，那么w会跟w2一起变动
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

---  

#### Next Steps

This notebook provided some information to get you started.

To learn more, please refer to your textbook and the links in the Sources section at top.